# Generated by Django 3.1.6 on 2021-03-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningProject', '0002_usage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usage',
            old_name='usage',
            new_name='apr',
        ),
        migrations.AddField(
            model_name='usage',
            name='aug',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='dec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='feb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='jan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='jul',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='jun',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='mar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='may',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='nov',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='oct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='sep',
            field=models.IntegerField(default=0),
        ),
    ]
