# Generated by Django 3.1.6 on 2021-03-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningProject', '0005_auto_20210325_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usage',
        ),
    ]
