# Generated by Django 3.1.6 on 2021-03-25 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LearningProject', '0006_delete_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jan', models.IntegerField(default=0)),
                ('feb', models.IntegerField(default=0)),
                ('mar', models.IntegerField(default=0)),
                ('apr', models.IntegerField(default=0)),
                ('may', models.IntegerField(default=0)),
                ('jun', models.IntegerField(default=0)),
                ('jul', models.IntegerField(default=0)),
                ('aug', models.IntegerField(default=0)),
                ('sep', models.IntegerField(default=0)),
                ('oct', models.IntegerField(default=0)),
                ('nov', models.IntegerField(default=0)),
                ('dec', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
