# Generated by Django 3.1.6 on 2021-03-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningProject', '0011_auto_20210325_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='apr',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='aug',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='dec',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='feb',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='jan',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='jul',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='jun',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='mar',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='may',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='nov',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='oct',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usage',
            name='sep',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
