# Generated by Django 3.1.6 on 2021-03-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningProject', '0012_auto_20210326_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usage',
            old_name='apr',
            new_name='Apr',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='aug',
            new_name='Aug',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='dec',
            new_name='Dec',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='feb',
            new_name='Feb',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='jan',
            new_name='Jan',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='jul',
            new_name='Jul',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='jun',
            new_name='Jun',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='mar',
            new_name='Mar',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='may',
            new_name='May',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='nov',
            new_name='Nov',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='oct',
            new_name='Oct',
        ),
        migrations.RenameField(
            model_name='usage',
            old_name='sep',
            new_name='Sep',
        ),
    ]
