# Generated by Django 3.1.6 on 2021-04-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningProject', '0015_usage_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='county',
            field=models.CharField(choices=[('cork', 'Cork'), ('dublin', 'Dublin'), ('kerry', 'Kerry')], default='none', max_length=25),
        ),
    ]
