# Generated by Django 3.1.6 on 2021-04-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningProject', '0018_auto_20210411_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='county',
            field=models.CharField(blank=True, choices=[('Cork', 'Cork'), ('Dublin', 'Dublin'), ('Kerry', 'Kerry')], max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='county',
            field=models.CharField(choices=[('Cork', 'Cork'), ('Dublin', 'Dublin'), ('Kerry', 'Kerry')], max_length=20),
        ),
    ]
