# Generated by Django 3.1.6 on 2021-04-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningProject', '0020_usage_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='reduction_percentage',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
