# Generated by Django 3.1.6 on 2021-04-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningProject', '0021_usage_reduction_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='standing_charge',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
