# Generated by Django 3.1.6 on 2021-04-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningProject', '0023_usage_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='rate',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
