# Generated by Django 3.1.6 on 2021-04-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningProject', '0024_auto_20210412_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='gas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='oil',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
