# Generated by Django 3.1.6 on 2021-04-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningProject', '0025_auto_20210413_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='oil_frequency',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
