# Generated by Django 3.1.6 on 2021-04-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningProject', '0026_usage_oil_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='electricity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
