# Generated by Django 3.1.6 on 2021-04-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningProject', '0028_usage_greenmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='Apr_elec',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='Apr_gas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='Apr_oil',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='Mar_elec',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='Mar_gas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='Mar_oil',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
