# Generated by Django 3.1.6 on 2021-04-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningProject', '0029_auto_20210413_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='elec_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='gas_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='oil_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
