# Generated by Django 3.1.6 on 2021-04-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningProject', '0031_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testModel',
        ),
    ]
