# Generated by Django 3.1.6 on 2021-04-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningProject', '0032_delete_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='county',
            field=models.CharField(blank=True, choices=[('Cork', 'Cork'), ('Dublin', 'Dublin'), ('Kerry', 'Kerry')], default='', max_length=25),
        ),
    ]
