# Generated by Django 3.1.6 on 2021-04-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningProject', '0034_energypledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energypledge',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
