# Generated by Django 3.1.6 on 2021-05-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningProject', '0035_auto_20210430_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='Jun_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='Jun_elec',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='Jun_gas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='Jun_oil',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='May_cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='May_elec',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='May_gas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='May_oil',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
