# Generated by Django 3.1.6 on 2021-05-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningProject', '0036_auto_20210501_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage',
            name='Jun_cost',
        ),
        migrations.RemoveField(
            model_name='usage',
            name='May_cost',
        ),
    ]
